apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: radix-github-maintenance
rules:
  - apiGroups: ['*']
    resources: ['pods']
    verbs: ['get', 'list']
  - apiGroups: ['*']
    resources: ['secrets']
    verbs: ['get', 'create', 'list', 'patch']
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['get', 'patch']
  - apiGroups: ['apps']
    resources: ['deployments/scale']
    verbs: ['patch']
  - apiGroups: ['networking.k8s.io']
    resources: ['ingresses']
    verbs: ['get']
  - apiGroups: ['kustomize.toolkit.fluxcd.io']
    resources: ['kustomizations']
    verbs: ['get', 'list', 'watch', 'patch']
