environment: "c3"
flux_folder: "c3"
cluster_type: "production"
subscription_shortname: "s940"
location: "swedencentral"
secondary_location: "westeurope"
developers: ["0e0d22c6-9f03-48a5-89be-be7b060c8a32"] # AZ PIM OMNIA RADIX Cluster Admin - prod
zoneconfig:
  RADIX_API_REQUIRE_APP_CONFIGURATION_ITEM: "true"
  RADIX_API_REQUIRE_APP_AD_GROUPS: "true"
  APP_REGISTRATION_NETWORKPOLICY_CANARY: "ar-radix-networkpolicy-canary"
  
backend:
  resource_group_name: "s940-tfstate"
  storage_account_name: "s940radixinfra"
  container_name: "infrastructure"
  subscription_id: "ded7ca41-37c8-4085-862f-b11d21ab341a"
  tenant_id: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
  ip_key_vault_id: "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/common-c3/providers/Microsoft.KeyVault/vaults/radix-keyv-c3"
  terraform_storage_id: "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/s940-tfstate/providers/Microsoft.Storage/storageAccounts/s940radixinfra"
networksets:
  networkset1:
    vnet: "10.8.0.0"
    ingressIP:  "20.91.128.160"
    istioIP:    "20.91.128.163"
    egress:
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-egress-radix-aks-c3-prod-001"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-egress-radix-aks-c3-prod-002"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-egress-radix-aks-c3-prod-003"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-egress-radix-aks-c3-prod-004"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-egress-radix-aks-c3-prod-005"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-egress-radix-aks-c3-prod-006"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-egress-radix-aks-c3-prod-007"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-egress-radix-aks-c3-prod-008"
  networkset2:
    vnet: "10.9.0.0"
    ingressIP: "20.91.128.161"
    istioIP:    "20.91.128.164"
    egress:
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-001"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-002"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-003"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-004"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-005"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-006"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-007"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-008"
  networkset3:
    vnet: "10.10.0.0"
    ingressIP:  "20.91.128.162"
    istioIP:    "20.91.128.165"
    egress:
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-009"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-0010"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-011"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-012"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-013"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-014"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-015"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-016"
clusters:
  c3-1:
    aksversion: "1.32.5"
    networkset: "networkset1"
    network_policy: "cilium"
    activecluster: false
