environment: "c3"
flux_folder: "c3"
cluster_type: "production"
subscription_shortname: "s940"
location: "swedencentral"
secondary_location: "westeurope"
developers: ["0e0d22c6-9f03-48a5-89be-be7b060c8a32"] # AZ PIM OMNIA RADIX Cluster Admin - prod
zoneconfig:
  RADIX_API_REQUIRE_APP_CONFIGURATION_ITEM: "true"
  RADIX_API_REQUIRE_APP_AD_GROUPS: "true"
  APP_REGISTRATION_NETWORKPOLICY_CANARY: "ar-radix-networkpolicy-canary"
  
backend:
  resource_group_name: "s940-tfstate"
  storage_account_name: "s940radixinfra"
  container_name: "infrastructure"
  subscription_id: "ded7ca41-37c8-4085-862f-b11d21ab341a"
  tenant_id: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
  ip_key_vault_id: "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/common-c3/providers/Microsoft.KeyVault/vaults/radix-keyv-c3"
  terraform_storage_id: "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/s940-tfstate/providers/Microsoft.Storage/storageAccounts/s940radixinfra"
networksets:
  networkset1:
    vnet: "10.11.0.0"
    ingressIP:  "51.12.145.16"
    gatewayPIP: "pip-ingress-radix-aks-c3-swedencentral-005"
    egress:
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-001"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-002"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-003"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-004"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-005"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-006"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-007"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-008"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-009"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-010"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-011"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-012"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-013"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-014"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-015"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-016"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-017"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-018"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-019"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-020"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-021"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-022"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-023"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-024"
  networkset2:
    vnet: "10.12.0.0"
    ingressIP: "51.12.145.18"
    gatewayPIP: "pip-ingress-radix-aks-c3-swedencentral-008"
    egress:
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-025"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-026"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-027"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-028"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-029"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-030"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-031"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-032"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-033"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-034"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-035"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-036"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-037"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-038"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-039"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-040"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-041"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-042"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-043"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-044"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-045"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-046"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-047"
      - "/subscriptions/ded7ca41-37c8-4085-862f-b11d21ab341a/resourceGroups/clusters-c3/providers/Microsoft.Network/publicIPAddresses/pip-radix-aks-c3-swedencentral-048"
clusters:
  c3-50:
    aksversion: "1.33.5"
    networkset: "networkset1"
    network_policy: "cilium"
    dns_wildcard: nginx # Options: "nginx" or "istio"
    activecluster: true
